# Generated by Django 4.1.7 on 2023-05-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_id',
            new_name='order_id',
        ),
    ]
