# Generated by Django 4.1.7 on 2023-05-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_stripe_payment_id_payment_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
