# Generated by Django 4.1.7 on 2023-03-03 17:17

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='projects.category')),
            ],
            options={
                'ordering': ['-updated_on', '-created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id', '-updated_on', '-created_on'], name='projects_pr_id_c15ae5_idx'),
        ),
    ]
