# Generated by Django 4.1.7 on 2023-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='choice',
            field=models.CharField(blank=True, choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
