# Generated by Django 4.1.7 on 2023-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos'),
        ),
    ]
