# Generated by Django 4.1.7 on 2023-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursecontent_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='download_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
