# Generated by Django 4.1.7 on 2023-05-02 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('courses', '0005_alter_course_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourse',
            new_name='Enrollment',
        ),
    ]
