# Generated by Django 4.1.7 on 2023-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursecontent_download_link_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
