# Generated by Django 4.1.7 on 2023-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
