# Generated by Django 4.1.7 on 2023-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='course_videos'),
        ),
    ]
