# Generated by Django 4.1.7 on 2023-05-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursecontent_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='video_url',
            new_name='video',
        ),
    ]
