# Generated by Django 4.1.7 on 2023-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_video_url_coursecontent_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='video',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
